[versions]
agp = "8.10.1"
appcompat = "1.7.1"
material = "1.12.0"
activity = "1.10.1"
constraintlayout = "2.2.1"
googleExoplayerVersion = "2.19.1"
media3Exoplayer = "1.8.0"

[libraries]
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
com-google-android-exoplayer-exoplayer = { module = "com.google.android.exoplayer:exoplayer", version.ref = "googleExoplayerVersion" }
exoplayer-ui = { module = "com.google.android.exoplayer:exoplayer-ui", version.ref = "googleExoplayerVersion" }
media3-common = { module = "androidx.media3:media3-common", version.ref = "media3Exoplayer" }
media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3Exoplayer" }
media3-exoplayer-dash = { module = "androidx.media3:media3-exoplayer-dash", version.ref = "media3Exoplayer" }
media3-transformer = { module = "androidx.media3:media3-transformer", version.ref = "media3Exoplayer" }
media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3Exoplayer" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

